# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestGoogleAuth' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestGoogleAuth
  pod 'GTMAppAuth'

end
